/* eslint-disable */

declare module 'glob:./sources/{*.ts,**/index.ts}' {
  export const aiml: typeof import('./sources/aiml')
  export const allsides: typeof import('./sources/allsides')
  export const arstechnica: typeof import('./sources/arstechnica')
  export const bbc: typeof import('./sources/bbc')
  export const bleacherreport: typeof import('./sources/bleacherreport')
  export const cnn: typeof import('./sources/cnn')
  export const crypto: typeof import('./sources/crypto')
  export const entertainment: typeof import('./sources/entertainment')
  export const espn: typeof import('./sources/espn')
  export const finance: typeof import('./sources/finance')
  export const github: typeof import('./sources/github')
  export const googlenews: typeof import('./sources/googlenews')
  export const hackernews: typeof import('./sources/hackernews')
  export const pbsnewshour: typeof import('./sources/pbsnewshour')
  export const producthunt: typeof import('./sources/producthunt')
  export const propublica: typeof import('./sources/propublica')
  export const reddit: typeof import('./sources/reddit')
  export const reuters: typeof import('./sources/reuters')
  export const science: typeof import('./sources/science')
  export const selfhosted: typeof import('./sources/selfhosted')
  export const slashdot: typeof import('./sources/slashdot')
  export const steam: typeof import('./sources/steam')
  export const theverge: typeof import('./sources/theverge')
  export const youtube: typeof import('./sources/youtube')
}
